### ISSUE TITLE
`Retention time` field for log-compacted events is not updated via Clin

### ISSUE THREAD

**Issue by Dmitry-Erokhin** [zalando-incubator/clin#11]
## Expected Behavior
Clin update event type retention policy for all event types, even log compacted (to the default value)

## Actual Behavior
The retention time field is not pushed to the Nakadi for log compacted event types.

## Description
As far as event type is log-compacted, the cleanup field is not actually used by Nakadi. However, it presents in the payloads leading to such divergences (which is impossible to fix via Clin):
```
⦿ Found 1 changes: event type _____
    values_changed:
      root.cleanup.retention_time_days:
        new_value: 1
        old_value: 4
```

## Steps to Reproduce the Problem
  1. Create log-compacted event type in Nakadi via Clin
  2. Update retention policy via any HTTP client
  3. Reprocess file via Clin

## Specifications
  - Version: 1.0.0
  - Platform: MacOS
  - Subsystem:
